package exeptionHandling;

public class assign3  {
		
		public static void main(String[] args) {	
			try {
				int arr1[]= new int[-2];
					
				
			}
			catch(Exception e)
			{
				System.out.println(e);
			}
			finally{
				System.out.println("Final block");
			}
		}

	
}
